backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

# Enable editorial workflow for content approval
publish_mode: editorial_workflow

collections:
  - name: "config"
    label: "Site Configuration"
    files:
      - file: "site-config.json"
        label: "Site Settings"
        name: "site"
        fields:
          - {label: "Artist Name", name: "artist_name", widget: "string", default: "izuminka.tt"}
          - {label: "Site Title", name: "title", widget: "string", default: "izuminka.tt - Fineline Tattoo Artist"}
          - {label: "Site Description", name: "description", widget: "text", default: "Professional fineline tattoo artist specializing in delicate, minimalist designs"}
          - {label: "Contact Email", name: "email", widget: "string", default: "hello@izuminka.tt"}
          - {label: "Phone", name: "phone", widget: "string", required: false}
          - {label: "Instagram Handle", name: "instagram", widget: "string", default: "@izuminka.tt"}
          - {label: "Instagram URL", name: "instagram_url", widget: "string", default: "https://instagram.com/izuminka.tt"}
          - {label: "Studio Address", name: "studio_address", widget: "text", default: "123 Art Street\nCreative District\nBarcelona, Spain"}
          - {label: "Business Hours", name: "hours", widget: "text", default: "Tuesday - Saturday\n10:00 AM - 7:00 PM\nBy appointment only"}
          - {label: "Studio Location (Google Maps)", name: "maps_url", widget: "string", required: false}

  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tattoo Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Category", name: "category", widget: "select", options: ["botanical", "geometric", "script", "symbolic", "custom"]}
      - {label: "Size", name: "size", widget: "select", options: ["small", "medium", "large"]}
      - {label: "Client Location", name: "location", widget: "string", required: false}
      - {label: "Completion Date", name: "date", widget: "date", required: false}
      - {label: "Show in Portfolio", name: "published", widget: "boolean", default: true}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}

  - name: "pages"
    label: "Page Content"
    files:
      - file: "content/hero.md"
        label: "Hero Section"
        name: "hero"
        fields:
          - {label: "Artist Name", name: "artist_name", widget: "string", default: "izuminka.tt"}
          - {label: "Subtitle", name: "subtitle", widget: "string", default: "Fineline Tattoo Artist"}
          - {label: "Description", name: "description", widget: "text", default: "Creating delicate, minimalist tattoos that tell your unique story through fine lines and elegant details."}
          - {label: "Primary Button Text", name: "primary_button", widget: "string", default: "Book Consultation"}
          - {label: "Secondary Button Text", name: "secondary_button", widget: "string", default: "View Portfolio"}
          - {label: "Hero Image", name: "hero_image", widget: "image", required: false}
          - {label: "About Text", name: "about_text", widget: "markdown", default: "With over 5 years of experience in fineline tattooing, I specialize in minimalist designs, botanical illustrations, and custom pieces that reflect each client's personal story."}
          - label: "Specialties"
            name: "specialties"
            widget: "list"
            default: ["Fineline botanical tattoos", "Minimalist geometric designs", "Delicate script and lettering", "Custom symbolic pieces", "Small detailed artwork"]
            field: {label: "Specialty", name: "specialty", widget: "string"}

      - file: "content/booking.md"
        label: "Booking Section"
        name: "booking"
        fields:
          - {label: "Section Title", name: "title", widget: "string", default: "Book Your Session"}
          - {label: "Lead Text", name: "lead", widget: "text", default: "Ready to bring your vision to life? Let's discuss your unique design and create something beautiful together."}
          - {label: "Consultation Fee", name: "consultation_fee", widget: "string", default: "€50"}
          - {label: "Session Duration", name: "session_duration", widget: "string", default: "2-4 hours typically"}
          - {label: "Response Time", name: "response_time", widget: "string", default: "I'll respond within 24 hours to discuss your design and schedule a consultation."}

      - file: "content/contact.md"
        label: "Contact Section"
        name: "contact"
        fields:
          - {label: "Section Title", name: "title", widget: "string", default: "Get in Touch"}
          - {label: "Description", name: "description", widget: "text", default: "Have questions or want to see more work? Connect with me on Instagram or visit the studio."}
          - {label: "Studio Address", name: "studio_address", widget: "text", default: "123 Art Street\nCreative District\nBarcelona, Spain"}
          - {label: "Business Hours", name: "hours", widget: "text", default: "Tuesday - Saturday\n10:00 AM - 7:00 PM\nBy appointment only"}
          - {label: "Email", name: "email", widget: "string", default: "hello@izuminka.tt"}
          - {label: "Phone", name: "phone", widget: "string", required: false}
          - {label: "Instagram URL", name: "instagram_url", widget: "string", default: "https://instagram.com/izuminka.tt"}
          - {label: "Instagram Handle", name: "instagram_handle", widget: "string", default: "@izuminka.tt"}

  - name: "pricing"
    label: "Pricing & Services"
    files:
      - file: "content/pricing.json"
        label: "Pricing Information"
        name: "pricing"
        fields:
          - label: "Price List"
            name: "prices"
            widget: "list"
            fields:
              - {label: "Service", name: "service", widget: "string"}
              - {label: "Price", name: "price", widget: "string"}
              - {label: "Details", name: "details", widget: "string"}
              - {label: "Duration", name: "duration", widget: "string", required: false}
          - label: "Payment Methods"
            name: "payment_methods"
            widget: "list"
            default: ["Cash", "Bank transfer", "Credit/debit cards"]
            field: {label: "Method", name: "method", widget: "string"}
          - {label: "Deposit Amount", name: "deposit", widget: "string", default: "50%"}
          - {label: "Touch-up Policy", name: "touchup", widget: "text", default: "Free within 6 months, €75 after 6 months"}

  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        field: {label: "Tag", name: "tag", widget: "string"}
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["tattoo-care", "design-process", "studio-news", "artist-tips", "client-stories"]
      - {label: "Published", name: "published", widget: "boolean", default: false}

  - name: "testimonials"
    label: "Testimonials"
    folder: "content/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Client Name", name: "name", widget: "string"}
      - {label: "Tattoo Description", name: "tattoo", widget: "string", required: false}
      - {label: "Testimonial", name: "testimonial", widget: "text"}
      - {label: "Rating", name: "rating", widget: "number", min: 1, max: 5, default: 5}
      - {label: "Date", name: "date", widget: "date", required: false}
      - {label: "Show Testimonial", name: "published", widget: "boolean", default: true}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}

  - name: "settings"
    label: "SEO & Analytics"
    files:
      - file: "content/seo-settings.json"
        label: "SEO Settings"
        name: "seo"
        fields:
          - {label: "Default SEO Title", name: "default_title", widget: "string", default: "izuminka.tt - Fineline Tattoo Artist"}
          - {label: "Default SEO Description", name: "default_description", widget: "text", default: "Professional fineline tattoo artist specializing in delicate, minimalist designs. Book your consultation today."}
          - {label: "Keywords", name: "keywords", widget: "text", default: "fineline tattoo, minimalist tattoo, botanical tattoo, Barcelona tattoo artist, delicate tattoo"}
          - {label: "Google Analytics ID", name: "google_analytics", widget: "string", required: false}
          - {label: "Google Search Console", name: "google_console", widget: "string", required: false}
          - {label: "Facebook Pixel ID", name: "facebook_pixel", widget: "string", required: false}
          - {label: "Favicon", name: "favicon", widget: "image", required: false}
          - {label: "Open Graph Image", name: "og_image", widget: "image", required: false}
          - {label: "Site Language", name: "language", widget: "string", default: "en"}
          - {label: "Time Zone", name: "timezone", widget: "string", default: "Europe/Madrid"}
